# Author: Travis Rosen
# Date: 6/13/2021
# Title: Rosen-Composers.yaml
# Description: YAML file describing the Composer API


openapi: 3.0.0
info:
  title: Composer API 
  version: "1.0"
  description: Composer API with YAML
# Start of paths section
paths: 
  # /composers will define both the get and post methods for the operations: FindAllComposers & createComposer
  /composers:
    get:
      summary: Returns a list of composer documents
      description: API for returning a list of composers from MongoDB Atlas
      responses:
        "200":
          description: Composer Documents
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
    post:
      summary: Creates a new composer object
      description: API for adding new composer objects
      requestBody:
        description: Composer's Information
        content:
          applications/json:
            schema:
              type: "object"
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        "200":
          description: User Added
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
  # /composers/{id} will define the get method for operation findComposerById
  /composers/{id}:
    get:
      summary: Returns a composer document
      description: API for returning a single composer object from MongoDB
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The composerid requested by the user
      responses:
        "200":
          description: User Added
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception